#!/usr/bin/env python3
"""
Test suite for Arc2DTokenizer to verify tokenization correctness.

Run with: python -m src.tests.test_tokenizer
"""

import sys
import torch
import numpy as np
from transformers import AutoModelForCausalLM

from src.data.tokenizer_2d import Arc2DTokenizer


def test_structural_token_roundtrip(tok: Arc2DTokenizer) -> bool:
    """Test that multi-token structural strings encode/decode correctly."""
    print("\n=== Test 1: Structural Token Round-trip ===")
    
    test_cases = [
        (" Input:", tok.TOK_INPUT),
        (" Output:", tok.TOK_OUTPUT),
        ("###", tok.TOK_PAIR_START),
        ("\n\n", tok.TOK_PAIR_END),
    ]
    
    all_passed = True
    for expected_str, tok_name in test_cases:
        ids = tok.structural_ids[tok_name]
        decoded = tok.tokenizer.decode(ids)
        passed = decoded == expected_str
        status = "✓" if passed else "✗"
        print(f"  {status} {tok_name}: {ids} -> '{repr(decoded)}' (expected '{repr(expected_str)}')")
        if not passed:
            all_passed = False
    
    return all_passed


def test_special_tokens_added(tok: Arc2DTokenizer) -> bool:
    """Test that special tokens are properly added after model initialization."""
    print("\n=== Test 2: Special Tokens Added ===")
    
    special_tokens = [
        tok.TOK_GRID_START,
        tok.TOK_GRID_END, 
        tok.TOK_ANSWER,
        tok.TOK_FIM_PREFIX,
        tok.TOK_FIM_SUFFIX,
        tok.TOK_FIM_MIDDLE,
        tok.TOK_FIM_HOLE,
    ]
    
    all_passed = True
    for tok_name in special_tokens:
        if tok_name not in tok.structural_ids:
            print(f"  ✗ {tok_name}: NOT FOUND in structural_ids")
            all_passed = False
        else:
            ids = tok.structural_ids[tok_name]
            if len(ids) != 1:
                print(f"  ✗ {tok_name}: Expected single-element list, got {ids}")
                all_passed = False
            else:
                decoded = tok.tokenizer.decode(ids)
                print(f"  ✓ {tok_name}: {ids} -> '{decoded}'")
    
    return all_passed


def test_build_sample(tok: Arc2DTokenizer) -> bool:
    """Test that build_sample produces correct tokenization."""
    print("\n=== Test 3: Build Sample ===")
    
    puzzle = {
        "train": [
            {"input": [[1, 2], [3, 4]], "output": [[5, 6], [7, 8]]}
        ],
        "test": [
            {"input": [[0, 1], [1, 0]], "output": [[1, 0], [0, 1]]}
        ]
    }
    
    try:
        sample = tok.build_sample(puzzle, inference_mode=False)
        decoded = tok.tokenizer.decode(sample["input_ids"].tolist())
        
        # Check for required substrings
        checks = [
            ("### Input:" in decoded or "### Input:" in decoded.replace(" ", ""), "Contains '### Input:'"),
            (" Output:" in decoded, "Contains ' Output:'"),
            ("<|grid_start|>" in decoded, "Contains '<|grid_start|>'"),
            ("<|grid_end|>" in decoded, "Contains '<|grid_end|>'"),
            ("<|answer|>" in decoded, "Contains '<|answer|>'"),
        ]
        
        print(f"  Decoded sequence (first 200 chars):\n    {decoded[:200]}...")
        print(f"  Decoded sequence (last 100 chars):\n    ...{decoded[-100:]}")
        
        all_passed = True
        for condition, description in checks:
            status = "✓" if condition else "✗"
            print(f"  {status} {description}")
            if not condition:
                all_passed = False
        
        return all_passed
        
    except Exception as e:
        print(f"  ✗ build_sample raised exception: {e}")
        return False


def test_inference_mode(tok: Arc2DTokenizer) -> bool:
    """Test that inference mode stops at the right place."""
    print("\n=== Test 4: Inference Mode ===")
    
    puzzle = {
        "train": [
            {"input": [[1, 2], [3, 4]], "output": [[5, 6], [7, 8]]}
        ],
        "test": [
            {"input": [[0, 1], [1, 0]], "output": [[1, 0], [0, 1]]}
        ]
    }
    
    try:
        sample = tok.build_sample(puzzle, inference_mode=True)
        decoded = tok.tokenizer.decode(sample["input_ids"].tolist())
        
        # Should end with "Output:" (the model needs to generate the rest)
        ends_correctly = decoded.rstrip().endswith("Output:")
        
        print(f"  Last 150 chars: ...{decoded[-150:]}")
        
        status = "✓" if ends_correctly else "✗"
        print(f"  {status} Ends with 'Output:'")
        
        # Should NOT contain <|answer|> (that's generated by the model)
        no_answer = "<|answer|>" not in decoded
        status = "✓" if no_answer else "✗"
        print(f"  {status} Does not contain '<|answer|>' (model generates this)")
        
        return ends_correctly and no_answer
        
    except Exception as e:
        print(f"  ✗ build_sample (inference_mode=True) raised exception: {e}")
        return False


def test_no_duplicate_colons(tok: Arc2DTokenizer) -> bool:
    """Test that Input:/Output: don't produce duplicate or missing text."""
    print("\n=== Test 5: No Duplicate/Missing Colons ===")
    
    puzzle = {
        "train": [
            {"input": [[1]], "output": [[2]]}
        ],
        "test": [
            {"input": [[3]], "output": [[4]]}
        ]
    }
    
    try:
        sample = tok.build_sample(puzzle, inference_mode=False)
        decoded = tok.tokenizer.decode(sample["input_ids"].tolist())
        
        # Count occurrences - should have exactly the right number
        # For 1 train pair + 1 test pair: 2 "Input:" and 2 "Output:"
        input_count = decoded.count("Input:")
        output_count = decoded.count("Output:")
        
        expected_input = 2
        expected_output = 2
        
        input_ok = input_count == expected_input
        output_ok = output_count == expected_output
        
        print(f"  Found {input_count} 'Input:' (expected {expected_input})")
        print(f"  Found {output_count} 'Output:' (expected {expected_output})")
        
        status = "✓" if input_ok else "✗"
        print(f"  {status} Correct number of 'Input:'")
        
        status = "✓" if output_ok else "✗"
        print(f"  {status} Correct number of 'Output:'")
        
        return input_ok and output_ok
        
    except Exception as e:
        print(f"  ✗ Exception: {e}")
        return False


def test_digit_tokens(tok: Arc2DTokenizer) -> bool:
    """Test that digit tokens are correct single tokens."""
    print("\n=== Test 6: Digit Tokens ===")
    
    all_passed = True
    for digit in range(10):
        tid = tok.digit_ids[digit]
        decoded = tok.tokenizer.decode([tid])
        passed = decoded == str(digit)
        status = "✓" if passed else "✗"
        print(f"  {status} Digit {digit}: token_id={tid}, decoded='{decoded}'")
        if not passed:
            all_passed = False
    
    return all_passed


def test_grid_extraction(tok: Arc2DTokenizer) -> bool:
    """Test that grids can be decoded from token sequences."""
    print("\n=== Test 7: Grid Extraction ===")
    
    puzzle = {
        "train": [
            {"input": [[1, 2, 3], [4, 5, 6]], "output": [[7, 8, 9], [0, 1, 2]]}
        ],
        "test": [
            {"input": [[0, 0], [0, 0]], "output": [[1, 1], [1, 1]]}
        ]
    }
    
    try:
        sample = tok.build_sample(puzzle, inference_mode=False)
        token_ids = sample["input_ids"].tolist()
        
        # Find the last <|grid_start|> to extract the last grid (test output)
        grid_start_id = tok.structural_ids[tok.TOK_GRID_START][0]
        last_grid_start = -1
        for i, tid in enumerate(token_ids):
            if tid == grid_start_id:
                last_grid_start = i
        
        if last_grid_start == -1:
            print("  ✗ No <|grid_start|> found in token sequence")
            return False
        
        # Decode starting from the last grid
        grid = tok.decode_grid(token_ids[last_grid_start + 1:])
        
        if grid is None:
            print("  ✗ decode_grid returned None")
            return False
        
        expected = np.array([[1, 1], [1, 1]])
        matches = np.array_equal(grid, expected)
        
        print(f"  Extracted grid:\n{grid}")
        print(f"  Expected:\n{expected}")
        
        status = "✓" if matches else "✗"
        print(f"  {status} Grid matches expected output")
        
        return matches
        
    except Exception as e:
        print(f"  ✗ Exception: {e}")
        import traceback
        traceback.print_exc()
        return False


def run_all_tests():
    """Run all tokenizer tests."""
    print("=" * 60)
    print("Arc2DTokenizer Test Suite")
    print("=" * 60)
    
    # Initialize tokenizer
    print("\nInitializing tokenizer...")
    tok = Arc2DTokenizer()
    
    # Test 1: Round-trip (doesn't need model)
    test1_passed = test_structural_token_roundtrip(tok)
    
    # Test 6: Digit tokens (doesn't need model)
    test6_passed = test_digit_tokens(tok)
    
    # For remaining tests, we need to add special tokens (requires model)
    print("\n" + "=" * 60)
    print("Loading model to add special tokens...")
    print("=" * 60)
    
    try:
        model = AutoModelForCausalLM.from_pretrained(
            "Qwen/Qwen3-4B-Thinking-2507",
            torch_dtype=torch.bfloat16,
            trust_remote_code=True,
        )
        tok.add_special_tokens_to_model(model)
        model_loaded = True
    except Exception as e:
        print(f"Failed to load model: {e}")
        print("Skipping tests that require special tokens...")
        model_loaded = False
    
    if model_loaded:
        test2_passed = test_special_tokens_added(tok)
        test3_passed = test_build_sample(tok)
        test4_passed = test_inference_mode(tok)
        test5_passed = test_no_duplicate_colons(tok)
        test7_passed = test_grid_extraction(tok)
    else:
        test2_passed = test3_passed = test4_passed = test5_passed = test7_passed = None
    
    # Summary
    print("\n" + "=" * 60)
    print("Test Summary")
    print("=" * 60)
    
    results = [
        ("1. Structural Token Round-trip", test1_passed),
        ("2. Special Tokens Added", test2_passed),
        ("3. Build Sample", test3_passed),
        ("4. Inference Mode", test4_passed),
        ("5. No Duplicate Colons", test5_passed),
        ("6. Digit Tokens", test6_passed),
        ("7. Grid Extraction", test7_passed),
    ]
    
    all_passed = True
    for name, result in results:
        if result is None:
            status = "SKIPPED"
        elif result:
            status = "PASSED"
        else:
            status = "FAILED"
            all_passed = False
        print(f"  {name}: {status}")
    
    print()
    if all_passed:
        print("All tests PASSED!")
        return 0
    else:
        print("Some tests FAILED!")
        return 1


if __name__ == "__main__":
    sys.exit(run_all_tests())
